#!/usr/bin/python3
"""raise with message"""


def raise_exception_msg(message=""):
    raise NameError(message)
